/* generated from the downloaded Kenney kits — model lists per kit */
window.KENNEY_KITS = [
 {
  "slug": "survival-kit",
  "name": "Survival Kit",
  "url": "https://kenney.nl/assets/survival-kit",
  "zone": "Startkamp",
  "models": [
   "bottle",
   "bottle-large",
   "bucket",
   "campfire-fishing-stand",
   "campfire-pit",
   "campfire-stand",
   "chest",
   "fence",
   "fence-doorway",
   "fence-fortified",
   "fish",
   "fish-large",
   "floor",
   "floor-hole",
   "floor-old",
   "grass",
   "grass-large",
   "patch-grass",
   "patch-grass-large",
   "resource-planks",
   "resource-stone",
   "resource-stone-large",
   "rock-a",
   "rock-b",
   "rock-c",
   "rock-flat",
   "rock-flat-grass",
   "rock-sand-a",
   "rock-sand-b",
   "rock-sand-c",
   "signpost",
   "signpost-single",
   "structure",
   "structure-canvas",
   "structure-floor",
   "structure-roof",
   "tent",
   "tent-canvas",
   "tool-axe",
   "tool-hammer",
   "tool-hoe",
   "tool-pickaxe",
   "tool-shovel",
   "tree",
   "tree-log",
   "tree-log-small",
   "tree-tall",
   "workbench",
   "workbench-anvil",
   "workbench-grind"
  ]
 },
 {
  "slug": "pirate-kit",
  "name": "Pirate Kit",
  "url": "https://kenney.nl/assets/pirate-kit",
  "zone": "Zinnenzee, Schip",
  "models": [
   "boat-row-large",
   "boat-row-small",
   "bottle",
   "bottle-large",
   "cannon",
   "cannon-ball",
   "cannon-mobile",
   "chest",
   "crate",
   "crate-bottles",
   "flag",
   "flag-high",
   "grass",
   "grass-plant",
   "hole",
   "mast",
   "mast-ropes",
   "palm-bend",
   "palm-detailed-bend",
   "palm-detailed-straight",
   "palm-straight",
   "patch-grass",
   "patch-grass-foliage",
   "patch-sand",
   "patch-sand-foliage",
   "platform",
   "platform-planks",
   "rocks-a",
   "rocks-b",
   "rocks-c",
   "rocks-sand-a",
   "rocks-sand-b",
   "rocks-sand-c",
   "ship-ghost",
   "ship-large",
   "ship-medium",
   "ship-pirate-large",
   "ship-pirate-medium",
   "ship-pirate-small",
   "ship-small",
   "ship-wreck",
   "structure",
   "structure-fence",
   "structure-fence-sides",
   "structure-platform",
   "structure-platform-dock",
   "structure-platform-dock-small",
   "structure-platform-small",
   "structure-roof",
   "tool-paddle"
  ]
 },
 {
  "slug": "modular-cave-kit",
  "name": "Modular Cave Kit",
  "url": "https://kenney.nl/assets/modular-cave-kit",
  "zone": "Geheime Grot",
  "models": [
   "corridor",
   "corridor-corner",
   "corridor-end",
   "corridor-intersection",
   "corridor-junction",
   "corridor-transition",
   "corridor-wide",
   "corridor-wide-corner",
   "corridor-wide-end",
   "corridor-wide-intersection",
   "corridor-wide-junction",
   "gate",
   "gate-metal-bars",
   "gate-overhang",
   "gate-rock",
   "ladder",
   "room-corner",
   "room-large",
   "room-large-variation",
   "room-small",
   "room-small-variation",
   "room-wide",
   "room-wide-variation",
   "stairs",
   "stairs-wide",
   "template-corner",
   "template-detail",
   "template-floor",
   "template-floor-big",
   "template-floor-detail",
   "template-floor-detail-a",
   "template-floor-layer",
   "template-floor-layer-hole",
   "template-floor-layer-raised",
   "template-wall",
   "template-wall-corner",
   "template-wall-detail-a",
   "template-wall-half",
   "template-wall-stairs",
   "template-wall-top"
  ]
 },
 {
  "slug": "mini-forest",
  "name": "Mini Forest",
  "url": "https://kenney.nl/assets/mini-forest",
  "zone": "Palmenbos",
  "models": [
   "bridge",
   "building-platform",
   "building-roof",
   "building-structure",
   "fence",
   "flag",
   "ladder",
   "patch-dirt",
   "patch-grass",
   "plant",
   "rocks-high",
   "rocks-low",
   "rocks-ramp",
   "stones",
   "target",
   "tent",
   "tree",
   "tree-high",
   "weapon-arrow",
   "weapon-bow"
  ]
 },
 {
  "slug": "fantasy-town-kit",
  "name": "Fantasy Town Kit",
  "url": "https://kenney.nl/assets/fantasy-town-kit",
  "zone": "Startkamp, dorp",
  "models": [
   "balcony-wall",
   "balcony-wall-fence",
   "banner-green",
   "banner-red",
   "blade",
   "cart",
   "cart-high",
   "fence",
   "fence-broken",
   "fence-curved",
   "fence-gate",
   "fountain-round",
   "fountain-round-detail",
   "overhang",
   "pillar-wood",
   "planks",
   "planks-half",
   "planks-opening",
   "poles",
   "poles-horizontal",
   "rock-large",
   "rock-small",
   "rock-wide",
   "roof-corner",
   "roof-corner-inner",
   "roof-corner-round",
   "roof-flat",
   "roof-gable-detail",
   "roof-gable-end",
   "roof-gable-top",
   "roof-left",
   "roof-point",
   "roof-right",
   "roof-window",
   "stairs-stone-corner",
   "stairs-stone-round",
   "stairs-wide-wood",
   "stairs-wide-wood-handrail",
   "stairs-wood",
   "stairs-wood-handrail",
   "tree",
   "tree-crooked",
   "tree-high",
   "tree-high-crooked",
   "tree-high-round",
   "wall-wood",
   "wall-wood-arch",
   "wall-wood-arch-top",
   "wall-wood-block",
   "wall-wood-block-half",
   "wall-wood-broken",
   "wall-wood-corner",
   "wall-wood-corner-diagonal",
   "wall-wood-corner-diagonal-half",
   "wall-wood-corner-edge",
   "wall-wood-curved",
   "wall-wood-detail-cross",
   "wall-wood-detail-diagonal",
   "wall-wood-detail-horizontal",
   "wall-wood-diagonal",
   "wall-wood-door",
   "wall-wood-doorway-base",
   "wall-wood-doorway-square",
   "wall-wood-doorway-square-wide-curved",
   "wall-wood-half",
   "wall-wood-rounded",
   "wall-wood-side",
   "wall-wood-slope",
   "wall-wood-window-glass",
   "wall-wood-window-round",
   "wall-wood-window-shutters",
   "watermill",
   "watermill-wide",
   "wheel",
   "windmill"
  ]
 },
 {
  "slug": "platformer-kit",
  "name": "Platformer Kit",
  "url": "https://kenney.nl/assets/platformer-kit",
  "zone": "Klimrots",
  "models": [
   "arrow",
   "arrows",
   "crate",
   "crate-strong",
   "fence-broken",
   "fence-corner",
   "fence-corner-curved",
   "fence-low-broken",
   "fence-low-corner",
   "fence-low-corner-curved",
   "fence-low-straight",
   "fence-rope",
   "fence-straight",
   "flowers",
   "flowers-tall",
   "grass",
   "heart",
   "ladder",
   "ladder-broken",
   "ladder-long",
   "lever",
   "lock",
   "mushrooms",
   "plant",
   "platform",
   "platform-fortified",
   "platform-overhang",
   "platform-ramp",
   "poles",
   "rocks",
   "sign",
   "spring",
   "star",
   "stones",
   "tree-pine",
   "tree-pine-small"
  ]
 },
 {
  "slug": "mini-dungeon",
  "name": "Mini Dungeon",
  "url": "https://kenney.nl/assets/mini-dungeon",
  "zone": "Vulkaanpad, Grot",
  "models": [
   "banner",
   "barrel",
   "chest",
   "coin",
   "column",
   "dirt",
   "floor",
   "floor-detail",
   "gate",
   "key",
   "pot",
   "rocks",
   "stairs",
   "stones",
   "trap",
   "wall",
   "wall-half",
   "wall-narrow",
   "wall-opening",
   "wood-structure",
   "wood-support"
  ]
 }
];
